"""shop sync tables

Revision ID: 9f471bff29aa
Revises: b6f2d4a1c8e0
Create Date: 2026-08-19 12:08:39.199778
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9f471bff29aa"
down_revision: str | None = "b6f2d4a1c8e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sales_aggregates",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("external_product_id", sa.String(length=300), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("orders", sa.Integer(), nullable=False),
        sa.Column("units", sa.Integer(), nullable=False),
        sa.Column("gross_revenue", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("refund_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("estimated_cogs", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("gross_margin", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_aggregates")),
        sa.UniqueConstraint(
            "tenant_id", "connection_id", "external_product_id", "date", name="uq_sales_daily"
        ),
    )
    op.create_index(
        op.f("ix_sales_aggregates_tenant_id"), "sales_aggregates", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_sales_tenant_connection_date",
        "sales_aggregates",
        ["tenant_id", "connection_id", "date"],
        unique=False,
    )
    op.create_table(
        "shop_intelligence_profiles",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sales_window_days", sa.Integer(), nullable=False),
        sa.Column(
            "category_revenue_share", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("category_unit_share", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("asp_percentiles", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "top_product_attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("repeat_purchase_proxy", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "inventory_turnover_by_category",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("seasonality_features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data_coverage", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shop_intelligence_profiles")),
        sa.UniqueConstraint("tenant_id", "connection_id", name="uq_shop_profile"),
    )
    op.create_index(
        op.f("ix_shop_intelligence_profiles_tenant_id"),
        "shop_intelligence_profiles",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "shop_product_snapshots",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("external_product_id", sa.String(length=300), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("category_path", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("cost", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("inventory_quantity", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("snapshot_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shop_product_snapshots")),
        sa.UniqueConstraint(
            "tenant_id", "connection_id", "external_product_id", name="uq_shop_product_external"
        ),
    )
    op.create_index(
        op.f("ix_shop_product_snapshots_tenant_id"),
        "shop_product_snapshots",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_shop_product_tenant_connection",
        "shop_product_snapshots",
        ["tenant_id", "connection_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_shop_product_tenant_connection", table_name="shop_product_snapshots")
    op.drop_index(op.f("ix_shop_product_snapshots_tenant_id"), table_name="shop_product_snapshots")
    op.drop_table("shop_product_snapshots")
    op.drop_index(
        op.f("ix_shop_intelligence_profiles_tenant_id"), table_name="shop_intelligence_profiles"
    )
    op.drop_table("shop_intelligence_profiles")
    op.drop_index("ix_sales_tenant_connection_date", table_name="sales_aggregates")
    op.drop_index(op.f("ix_sales_aggregates_tenant_id"), table_name="sales_aggregates")
    op.drop_table("sales_aggregates")
    # ### end Alembic commands ###
