"""trend raw observations

Revision ID: f345941f9f82
Revises: 9f471bff29aa
Create Date: 2026-08-19 14:11:53.442504
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f345941f9f82"
down_revision: str | None = "9f471bff29aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_trend_observations",
        sa.Column("candidate_id", sa.Uuid(), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("source_id", sa.String(length=300), nullable=False),
        sa.Column("title_raw", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("observed_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_trend_observations")),
        sa.UniqueConstraint("tenant_id", "source", "source_id", name="uq_raw_trend_source_item"),
    )
    op.create_index(
        op.f("ix_raw_trend_observations_tenant_id"),
        "raw_trend_observations",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_raw_trend_tenant_candidate",
        "raw_trend_observations",
        ["tenant_id", "candidate_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_raw_trend_tenant_candidate", table_name="raw_trend_observations")
    op.drop_index(op.f("ix_raw_trend_observations_tenant_id"), table_name="raw_trend_observations")
    op.drop_table("raw_trend_observations")
    # ### end Alembic commands ###
